In [ ]:
import numpy as np

In [51]:
class Neuron:

    def __init__(self,input_len,idx):
        self.bias = 1 # init bias to 1
        self.w = np.random.rand(input_len) # random value weight list, input_len is the dimension of the x_input vector
        self.output = 0 # init output to 0
        self.index = idx

    def printIndex(self):
        print("Neuron: ",self.index)

    def linearActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        return self.output

    def reluActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        if(self.output > 0):
            self.output = self.output
        else:
            self.output = 0
        return self.output

    def tanhActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        self.output = np.tanh(self.output)
        return self.output

    def sigmoidActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        self.output = 1 / (1+np.exp(-self.output))
        return self.output

    def softmaxActivation(self,x,k):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + np.exp(self.w[i] * x[i])
        self.output = np.exp(x[k]) / self.output
        return self.output

In [ ]:
class Layer:

    def __init__(self,lay_size):
        self.layer_size = lay_size
        self.neurons = []
        self.output_size = lay_size
        self.outputs = []
    
    def createNeurons(self,input_size):
        for i in range(0,self.layer_size):
            self.neurons.append(Neuron(input_size,i))
        return self.neurons

    def linearOutputs(self,x):
        self.outputs = []
        for i in range(0,self.layer_size):
            self.outputs.append(self.neurons[i].linearActivation(x))
        return self.outputs

    def reluOutputs(self,x):
        self.outputs = []
        for i in range(0,self.layer_size):
            self.outputs.append(self.neurons[i].reluActivation(x))
        return self.outputs
    
    def tanhOutputs(self,x):
        self.outputs = []
        for i in range(0,self.layer_size):
            self.outputs.append(self.neurons[i].tanhActivation(x))
        return self.outputs
    
    def sigmoidOutputs(self,x):
        self.outputs = []
        for i in range(0,self.layer_size):
            self.outputs.append(self.neurons[i].sigmoidActivation(x))
        return self.outputs

    def softmaxOutputs(self,x,k):
        self.outputs = []
        for i in range(0,self.layer_size):
            self.outputs.append(self.neurons[i].softmaxActivation(x,k))
        return self.outputs

In [ ]:
# Testing Layers of different sizes
x = np.array([1,1,1,1])
layer1_size = 8
layer2_size = 16
layer3_size = 32
'''Layer1 with 8 Neurons'''
myLayer1 = Layer(layer1_size)
'''Layer2 with 16 Neurons'''
myLayer2 = Layer(layer2_size)
'''Layer3 with 32 Neurons'''
myLayer3 = Layer(layer3_size)

# Testing Neurons creation for layers of different size
print("Layer 1")
myLayer1Neurons = myLayer1.createNeurons(len(x))
for i in range(0,layer1_size):
    myLayer1Neurons[i].printIndex()
    print(myLayer1Neurons[i].w)
    print(np.sum(myLayer1Neurons[i].w))

'''print("\n")
print("Layer 2")
myLayer2Neurons = myLayer2.createNeurons(len(x))
for i in range(0,layer2_size):
    myLayer2Neurons[i].printIndex()
    print(myLayer2Neurons[i].w)

print("\n")
print("Layer 3")
myLayer3Neurons = myLayer3.createNeurons(len(x))
for i in range(0,layer3_size):
    myLayer3Neurons[i].printIndex()
    print(myLayer3Neurons[i].w)'''

# Testing Layer outputs calculation for layer of different size
print("\n")
print("Layer Outputs")
print("linear output:",myLayer1.linearOutputs(x))
print("relu output:",myLayer1.reluOutputs(x))
print("tanh output:",myLayer1.tanhOutputs(x))
print("sigmoid output:",myLayer1.sigmoidOutputs(x))
print("softmax output:",myLayer1.softmaxOutputs(x,3))

In [53]:
# Testing Layers of different sizes
x = np.array([1,1,1,1])
layer1_size = 8
layer2_size = 16
layer3_size = 32
'''Layer1 with 8 Neurons'''
myLayer1 = Layer(layer1_size)
'''Layer2 with 16 Neurons'''
myLayer2 = Layer(layer2_size)

# Testing Neurons creation for layers of different size
print("Layer 1")
myLayer1Neurons = myLayer1.createNeurons(len(x))
for i in range(0,layer1_size):
    myLayer1Neurons[i].printIndex()
    print(myLayer1Neurons[i].w)
    print(np.sum(myLayer1Neurons[i].w))


# Testing Layer outputs calculation for layer of different size
l1_linearOutputs = myLayer1.linearOutputs(x)
l1_reluOutputs= myLayer1.reluOutputs(x)

print("\n")
print("Layer 2")
myLayer2Neurons = myLayer2.createNeurons(layer1_size) # layer1_size is now used for input dimension of layer 2 Neurons
for i in range(0,layer2_size):
    myLayer2Neurons[i].printIndex()
    print(myLayer2Neurons[i].w)

# Testing Layer outputs length of layer 2
print("\n")
print("Layer Outputs")
print("linear output:",myLayer2.linearOutputs(x))

Layer 1
Neuron:  0
[0.95288004 0.2392245  0.9064938  0.83250147]
2.9310998080789568
Neuron:  1
[0.05476278 0.3968844  0.02756982 0.92304877]
1.4022657700573224
Neuron:  2
[0.87592399 0.41166997 0.32372091 0.73184343]
2.343158307862258
Neuron:  3
[0.72492788 0.4250675  0.87879167 0.4946998 ]
2.5234868434325
Neuron:  4
[0.80134156 0.14781022 0.88056413 0.16605039]
1.9957663164174688
Neuron:  5
[0.67826509 0.82298979 0.14144108 0.60425722]
2.2469531737673227
Neuron:  6
[0.02156006 0.51839881 0.27364721 0.84389942]
1.6575055000226742
Neuron:  7
[0.52111468 0.27781027 0.87063318 0.67186156]
2.3414196914776486


Layer 2
Neuron:  0
[0.24790059 0.6791941  0.41787846 0.97275499 0.06306455 0.8529253
 0.15729149 0.18597353]
Neuron:  1
[0.17849497 0.04252327 0.45474282 0.71243722 0.29849454 0.44471193
 0.55327455 0.55830797]
Neuron:  2
[0.10145008 0.64557841 0.33884581 0.43871806 0.16555207 0.42000165
 0.77513677 0.03584418]
Neuron:  3
[0.43790369 0.96823567 0.51534392 0.84033797 0.20128703 0.4901