In [29]:
import numpy as np

In [47]:
class Neuron:

    def __init__(self,input_len,idx):
        self.bias = 1 # init bias to 1
        self.w = np.random.rand(input_len) # random value weight list
        self.output = 0 # init output to 0
        self.index = idx

    def printIndex(self):
        print("Neuron: ",self.index)

    def linearActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        return self.output

    def reluActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        if(self.output > 0):
            self.output = self.output
        else:
            self.output = 0
        return self.output

    def tanhActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        self.output = np.tanh(self.output)
        return self.output

    def sigmoidActivation(self,x):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + self.w[i] * x[i]
        self.output = 1 / (1+np.exp(-self.output))
        return self.output

    def softmaxActivation(self,x,k):
        self.output = self.bias
        for i in range(0,len(x)):
            self.output = self.output + np.exp(self.w[i] * x[i])
        self.output = np.exp(x[k]) / self.output
        return self.output

In [48]:
class Layer:

    def __init__(self,lay_size):
        self.layer_size = lay_size
        self.neurons = []
        self.output_size = lay_size
    
    def createNeurons(self,input_size):
        for i in range(0,self.layer_size):
            self.neurons.append(Neuron(input_size,i))
        return self.neurons

In [54]:
x = [1,1,1,1]
layer_size = 10
myLayer = Layer(layer_size)
myLayerNeurons = myLayer.createNeurons(len(x))
for i in range(0,layer_size):
    myLayerNeurons[i].printIndex()
    print(myLayerNeurons[i].w)

Neuron:  0
[0.34719865 0.22657607 0.08353575 0.714856  ]
Neuron:  1
[0.17350978 0.40862982 0.53366756 0.83810288]
Neuron:  2
[0.43242233 0.61909975 0.70812032 0.3156826 ]
Neuron:  3
[0.44673954 0.42742882 0.74643964 0.1241445 ]
Neuron:  4
[0.41024932 0.64809434 0.96026498 0.19597283]
Neuron:  5
[0.82782449 0.78995328 0.2386706  0.61197339]
Neuron:  6
[0.6030477  0.3277696  0.24834677 0.93522441]
Neuron:  7
[0.36444184 0.36981625 0.48595982 0.90597112]
Neuron:  8
[0.77783326 0.48636218 0.89021089 0.872197  ]
Neuron:  9
[0.87752951 0.81799373 0.77181475 0.18766998]
